# Generated by Django 5.2 on 2025-04-21 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_played',
            field=models.BooleanField(default=False),
        ),
    ]
