# Generated by Django 5.2 on 2025-04-28 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_player_total_score'),
    ]

    operations = [
        migrations.AddField(
            model_name='gameroom',
            name='game_started',
            field=models.BooleanField(default=False),
        ),
    ]
