# Generated by Django 5.2 on 2025-05-01 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_gameroom_game_started'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='balance',
            field=models.IntegerField(default=200),
        ),
        migrations.AddField(
            model_name='player',
            name='bet_amount',
            field=models.IntegerField(default=0),
        ),
    ]
