# Generated by Django 5.2 on 2025-05-01 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_player_balance_player_bet_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='player',
            name='has_bet',
            field=models.BooleanField(default=False),
        ),
    ]
